apiVersion: v1
kind: Pod
metadata: 
  name: multi-pod
  labels: 
    app: multi-pod
    type: network
spec: 
  containers:
    - name: 1st
      image: nginx:alpine
    - name: 2nd
      image: redis
    - name: 3rd
      image: memcached