apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: webshop
    service: nginx
spec:
  template:
    metadata:
      name: nginx-deploy
      labels:
        app: webshop
        service: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.8
  replicas: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 2
  selector:
    matchLabels:
      app: webshop
      service: nginx