apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: voting-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 80 #This is a serive port
      targetPort: 80 #This is the target port of the pods
      nodePort: 32000 #This port is enable on node to send the traffic
      protocol: TCP
  selector:
      app: vote
