apiVersion: v1
kind: Pod
metadata:
 name: demo-pod-2
spec:
 containers:
 - name: demo-container-1
   image: nginx
   resources:
     limits:
       memory: "90Mi"
       cpu: "10m"
     requests:
       memory: "70Mi"
       cpu: "6m"