apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: node-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 80 
      targetPort: 80 
      nodePort: 32000 
      protocol: TCP
  selector:
      app: node-app