apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deploy
  labels:
    app: mydeployment
    kind: frontend
spec:
  template:
    metadata:
      name: busybox-pod
      labels:
        app: web
        type: frontend
    spec:
      containers:
        - name: busybox-image
          image: busybox
          command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']

  replicas: 3
  selector:
    matchLabels:
      type: frontend