apiVersion: v1
kind: Pod
metadata:
  name: healthy-pod
  labels:
    app: goproxy
spec:
  containers:
  - name: healthy-pod
    image: nginx
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 1
      failureThreshold: 5
      periodSeconds: 3
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 1
      failureThreshold: 7
      periodSeconds: 3